---
- repo: https://github.com/ansible/ansible-lint.git
  rev: v5.1.3
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
    - id: yamllint
      entry: yamllint .
      types: [file, yaml]
