namespace: rhjhunt
name: lemp
version: 1.0.0
readme: README.md
authors:
- Jacob Hunt (https://github.com/rhjhunt)
description: Collection to create a LEMP stack
license:
- GPL-3.0-or-later
license_file: ''
tags:
  - lemp
  - nginx
  - mariadb
  - php
dependencies: {}
repository: https://github.com/rhjhunt/lemp
documentation: ''
homepage: https://github.com/rhjhunt/lemp
issues: https://github.com/rhjhunt/lemp/issues
build_ignore:
  - .vale.ini
  - .yamllint
  - .markdownlint.json
  - .github
  - .gitignore
  - . '*.tar.gz'
  - /venv